---

- debug: var=hostvars['localhost']['controller_hostname_list']['stdout_lines']

- name : get haproxy url 
  shell : >
    grep -m1 "bind " {{haproxy_config}} | awk '{print $2}'| cut -d ':' -f 1
  register: haproxy_ip_address
  become: true  

- name: remove nagios block in /tmp/haproxy/haproxy.cfg
  blockinfile:
    dest: "{{haproxy_config}}"
    marker: '# {mark} nagios marker'
    content: ""
    state: absent
  become: true


- name: insert/update nagios block in /tmp/haproxy/haproxy.cfg
  blockinfile:
    dest: "{{haproxy_config}}"
    marker: '# {mark} nagios marker'
    block: |
      listen nagios
        bind  {{haproxy_ip_address}}:54321 transparent
  become: true

- name: insert/update nagios block in /tmp/haproxy/haproxy.cfg
  blockinfile:
    dest: "{{haproxy_config}}"
    marker: "#DELETE#"
    insertbefore : '# END nagios marker'
    block: |
       #DELETE#    
          server {{item}}:54321 check fall 5 inter 2000 rise 2
  with_items: "{{hostvars['localhost']['controller_hostname_list']['stdout_lines']}}"
  become: true

- name: Remove markers ##DELETE##
  shell: >
    sed -i  '/#DELETE#/d' "{{haproxy_config}}"
  become: true 
